### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by WenXin20** [itayfeder/TintedPublic#2]
```
Minecraft v1.19.2
Forge v43.1.47
Tinted v1.1.0
```

When installed on my server, it crashes

[Crash Report](https://gist.github.com/WenXin20/4892e664b42d959562b3221bc6d7c7a9)
[Log](https://gist.github.com/WenXin20/5227e2c2850f11797dcac963b253f214)

**Comment by itayfeder** [comment]
Hello! let me look into it.

**Comment by itayfeder** [comment]
Hello! The problem should be fixed in version 1.1.1

**Comment by WenXin20** [comment]
Thanks! I'll give it a try

**Comment by WenXin20** [comment]
all fixed :)
