### ISSUE TITLE
What are the unofficial port permissions?

### ISSUE THREAD

**Issue by MerchantPug** [itayfeder/TintedPublic#3]
Hey, so if I were to make an unofficial as 1:1 port as possible for Fabric and/or Quilt (I can do Quilt exclusive if you have issues with the Fabric team like I do).

1. Would I be allowed, if you are to say no, I will not port such a mod and 2 can be left unanswered.
2. What are the terms and conditions on such a thing. 
Like, will I have access to any of the Forge version's source for the matter, will I not, what do you want in terms of being linked back for the original?
3. Additionally, what exactly is the license for the mod? It says MIT on CurseForge but this repo is ARR. Some clarification would be nice.

**Comment by itayfeder** [comment]
Hello! I'm glad you want to make a Fabric port of this mod, but sadly, I cannot allow it.
The reason is that this mod is very close to my heart, and I am already planning a port to fabric in the future.

However, I am not a fabric modder, so if I will have a problem, I will be sure to contact you.

**Comment by MerchantPug** [comment]
Thanks for the heads up about this. That's no problem for me.
