### ISSUE TITLE
[Crash] Seems like 1.1.1 crashing with Farmers Delight

### ISSUE THREAD

**Issue by murao-kun** [itayfeder/TintedPublic#5]
[crash-2022-11-12_20.50.36-client.txt](https://github.com/itayfeder/TintedPublic/files/9995570/crash-2022-11-12_20.50.36-client.txt)

**Comment by itayfeder** [comment]
I have seen this issue before, and I have a fix for it coming up in the next update

**Comment by murao-kun** [comment]
Tested. Fixed. Thank you!
